### ISSUE TITLE
Historical data crawler seems to be broken

### ISSUE THREAD

**Issue by jacoboermen** [avalanchesiqi/youtube-insight#2]
The code works great apart from the 'insights'-component. I fail to get any insights-data and cannot reproduce the example you provide. It gives me this error:

Message: '--- Socket timed out in historical data crawler:'
Arguments: ('HTTP Error 404: Not Found',)

Thanks for sharing your novel approach to YouTube-crawling and I hope it is possible to fix this issue.

**Comment by avalanchesiqi** [comment]
Hi,

There have been some changes on the YouTube side, in short they have disabled the request url that can retrieves the insight-data. Till this point I can not do much to make the insight component work again. Sorry about that. I shall modify the README to reflect this change in near future.

If you want to study the YouTube dynamics you can look at our published data. We have 2 more datasets that contain more information (tweets about these videos, google search volume and the recommendation network). We hope to publish these datasets later this year.

But unfortunately we can't help you get any new insight-data at this stage.

**Comment by jacoboermen** [comment]
Thanks. I was suspecting this. Hopefully, Google will allow similar data to be retrieved at a later point.
Great work and thanks for sharing code and data (which I will certainly look at).

**Comment by avalanchesiqi** [comment]
This package is no longer working since YouTube deprecated the insight endpoint around Nov, 2018.
